export const SET_ERROR = 'SESSION/SET_ERROR'

export const HIDE_ALERT = 'SESSION/HIDE_ALERT';

export const AUTH_SUCCESS = 'SESSION/AUTH_SUCCESS'

export const AUTH_FAILURE = 'SESSION/AUTH_FAILURE'

export const SESSION_REQUEST = 'SESSION/REQUEST'

export const LOG_OUT = 'SESSION/LOG_OUT'

//============= student

export const STUDENT_REQUEST = 'STUDENT/REQUEST'

export const GET_SUBJECTS_SUCCESS = 'STUDENT/GET_SUBJECTS_SUCCESS'

export const GET_SUBJECTS_FAILURE = 'STUDENT/GET_SUBJECTS_FAILURE'

//============= teacher