export const SET_ERROR = 'SESSION/SET_ERROR'

export const HIDE_ALERT = 'SESSION/HIDE_ALERT';

export const REGISTER_SUCCESS = 'SESSION/REGISTER_SUCCESS'

export const REGISTER_FAILURE = 'SESSION/REGISTER_FAILURE'

export const REQUEST = 'SESSION/REQUEST'

export const LOG_SUCCESS = 'SESSION/LOG_SUCCESS'

export const LOG_FAILURE = 'SESSION/LOG_FAILURE'