export const SET_ERROR = 'SESSION/SET_ERROR'

export const HIDE_ALERT = 'SESSION/HIDE_ALERT';

export const AUTH_SUCCESS = 'SESSION/AUTH_SUCCESS'

export const AUTH_FAILURE = 'SESSION/AUTH_FAILURE'

export const SESSION_REQUEST = 'SESSION/REQUEST'

export const LOG_OUT = 'SESSION/LOG_OUT'

export const TOGGLE_THEME = 'SESSION/TOGGLE_THEME'

//============= student

export const STUDENT_REQUEST = 'STUDENT/REQUEST'

export const STUDENT_GROUP_REQUEST = 'STUDENT/STUDENT_GROUP_REQUEST'

export const GET_SUBJECTS_SUCCESS = 'STUDENT/GET_SUBJECTS_SUCCESS'

export const GET_SUBJECTS_FAILURE = 'STUDENT/GET_SUBJECTS_FAILURE'

export const STUDENT_OUT = 'STUDENT/OUT'

export const STUDENT_SUB_GROUP_SUCCESS ='STUDENT/GET_GROUP_SUCCESS'

export const STUDENT_SUB_GROUP_FAILURE ='STUDENT/GET_GROUP_FAILURE'

export const STUDENT_GET_FILE_REQUEST = 'STUDENT/GET_FILE_REQUEST'

export const STUDENT_GET_FILE_SUCCESS = 'STUDENT/GET_FILE_SUCCESS'

export const STUDENT_GET_FILE_FAILURE = 'STUDENT/GET_FILE_FAILURE'


//============= teacher

export const TEACHER_REQUEST = 'TEACHER/REQUEST'

export const GET_NEW_STUDENT_SUCCESS = 'TEACHER/GET_NEW_STUDENT_SUCCESS'

export const GET_NEW_STUDENT_FAILURE = 'TEACHER/GET_NEW_STUDENT_FAILURE'

export const GET_NEW_STUDENT_REQUEST = 'TEACHER/GET_STUDENT_REQUEST'

export const FORM_NEW_GROUP_SUCCESS = 'TEACHER/FORM_NEW_GROUP_SUCCESS'

export const FORM_NEW_GROUP_FAILURE = 'TEACHER/FORM_NEW_GROUP_FAILURE'

export const GET_PROFILE_SUCCESS = 'TEACHER/GET_PROFILE_SUCCESS'

export const GET_PROFILE_FAILURE = 'TEACHER/GET_PROFILE_FAILURE'

export const TEACHER_OUT = 'TEACHER/OUT'



export const GET_GROUP_REQUEST = 'TEACHER/GET_GROUP_REQUEST'

export const GET_GROUP_SUCCESS = 'TEACHER/GET_GROUP_SUCCESS'

export const GET_GROUP_FAILURE = 'TEACHER/GET_GROUP_FAILURE'

export const TEACHER_CLEAR_GROUP = 'TEACHER/CLEAR_GROUP_ERROR_NEWSTUDENTS'



export const TEACHER_SEND_MESSAGE_REQUEST = 'TEACHER/SEND_MSG_REQUEST'

export const TEACHER_SEND_MESSAGE_SUCCESS = 'TEACHER/SEND_MSG_SUCCESS'

export const TEACHER_SEND_MESSAGE_FAILURE = 'TEACHER/SEND_MSG_FAILURE'


export const TEACHER_EDIT_GROUP_REQUEST = 'TEACHER/EDIT_GROUP_REQUEST'

export const TEACHER_EDIT_GROUP_SUCCESS = 'TEACHER/EDIT_GROUP_SUCCESS'

export const TEACHER_EDIT_GROUP_FAILURE = 'TEACHER/EDIT_GROUP_FAILURE'


export const TEACHER_CLEAR_SAVECHANGE = 'TEACHER/CLEAR_SAVECHANGE_FLAG'

//CREATE NEW GROUP

export const TEACHER_CREATE_GROUP_REQUEST = 'TEACHER/CREATE_GROUP_REQUEST'

export const TEACHER_CREATE_GROUP_SUCCESS = 'TEACHER/CREATE_GROUP_SUCCESS'

export const TEACHER_CREATE_GROUP_FAILURE = 'TEACHER/CREATE_GROUP_FAILURE'

export const TEACHER_CLEAR_GROUPCREATE = 'TEACHER/CLEAR_GROUPCREATE_FLAG'

// SEND FILE

export const TEACHER_SEND_FILE_REQUEST = 'TEACHER/SEND_FILE_REQUEST'

export const TEACHER_SEND_FILE_SUCCESS = 'TEACHER/SEND_FILE_SUCCESS'

export const TEACHER_SEND_FILE_FAILURE = 'TEACHER/SEND_FILE_FAILURE'

// GET FILE:

export const TEACHER_GET_FILE_REQUEST = 'TEACHER/GET_FILE_REQUEST'

export const TEACHER_GET_FILE_SUCCESS = 'TEACHER/GET_FILE_SUCCESS'

export const TEACHER_GET_FILE_FAILURE = 'TEACHER/GET_FILE_FAILURE'

// DELETE FILE

export const TEACHER_DELETE_FILE_REQUEST = 'TEACHER/TEACHER_DELETE_FILE_REQUEST'

export const TEACHER_DELETE_FILE = 'TEACHER/DELETE_FILE'